import api from './api';
import { VaccinationCampaign } from '../types'; // Adjust path as needed if types are in a different location

export const campaignService = {
  // Get all vaccination campaigns
  getVaccinationCampaigns: (): Promise<VaccinationCampaign[]> => {
    return api.get('/campaigns/vaccination');
  },

  // Get a single vaccination campaign by ID
  // Note: Assumes backend supports GET /campaigns/vaccination/{id}
  getVaccinationCampaignById: (id: string): Promise<VaccinationCampaign> => {
    return api.get(`/campaigns/vaccination/${id}`);
  },

  // Create a new vaccination campaign
  // Backend sets default status (e.g., "PENDING_APPROVAL").
  // 'id' is generated by the backend.
  createVaccinationCampaign: (data: Omit<VaccinationCampaign, 'id' | 'status'>): Promise<VaccinationCampaign> => {
    return api.post('/campaigns/vaccination', data);
  },

  // Approve a vaccination campaign
  // No payload needed, just the ID in the path. Backend handles status change.
  approveCampaign: (id: string): Promise<VaccinationCampaign> => {
    return api.put(`/campaigns/vaccination/${id}/approve`, {}); // Sending empty object as payload for PUT if required
  },

  // Update a vaccination campaign
  // Note: Assumes backend supports PUT /campaigns/vaccination/{id} for general updates.
  // 'status' updates are typically handled by specific actions like 'approve'.
  // 'id' is path parameter.
  updateVaccinationCampaign: (id: string, data: Partial<Omit<VaccinationCampaign, 'id' | 'status'>>): Promise<VaccinationCampaign> => {
    return api.put(`/campaigns/vaccination/${id}`, data);
  },

  // Delete a vaccination campaign
  // Note: Assumes backend supports DELETE /campaigns/vaccination/{id}
  deleteVaccinationCampaign: (id: string): Promise<void> => {
    return api.delete(`/campaigns/vaccination/${id}`);
  }
};

// If there are other types of campaigns (e.g., health awareness),
// their service methods could be added here or in separate files,
// depending on how the frontend team wants to organize services.
// For example:
// export const healthAwarenessCampaignService = { ... };
